---
# Miscellaneous
- name: Install dependencies
  package:
    name:
      - procps
      - apparmor
      - micro
      - gpg
      - htop
      - zsh
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - ufw
      - lsb-release
    state: present
    update_cache: yes
  notify:
    - enable ufw

# Install Docker
- name: Create Docker's apt repository keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "a+r"

- name: Determine architecture for Docker repo
  set_fact:
    docker_arch: "{{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | default(omit) }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker Engine, CLI, and Plugins
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
  notify:
    - enable docker
