all:
  hosts:
    nubecita.remote:
      ansible_host: nubecita.dev
  vars:
    ansible_user: larry
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    timezone: "Europe/Madrid"

  children:
    hetzner:
      hosts:
        nubecita.remote:
          users:
            larry:
              sudo: true
              ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG9K27LQ9VewIvxAcrR01VEw0/IpaRXuO19WhyT9372r larrywtf609@gmail.com"
            runner:
              sudo: true
              ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTJ15E3ljGVcMfjhKPgheEocDny0ZXurRbzA/AD3ajuGmo040/kwG5yJDp9o/qjrG5OOt9z4td6GfJtxy5uZwLhKIT3c8INOHDthvJT5lSkoCHjH5qVnFwn7YTJrVUUGMJk1qgfq47fthrf3aOt2gUbxisPrAUd3aLOXkNlauni/CdZqrG8hbsvoUjgpy09URyrY6IyBR2I4gV7CRuaNO2jVW87lduv8ckuNrQAfhEG2rWKvpxLi9S8BKp1Q9vemg8lXEXl2BmSSJ773y9WTMmi/jnmQ0WS06pUwkV/Cet4C4shuzI46QD/n/aDZbzZb4RMT6rI2LpVyIRbb8f6HLFDqQ4SVMIycG02wm1SeAvHkdvnRFYDWrEPg774a401wAKboNvOf4Qw1FvB3i2UyUOsksurJZxvnehY77GmX/qFHHhQKqDBsb6JN9MPM5KEDe++IMuVE8DwB+4XlgVRenofv2zIMGexxXlw8yu/HPKbUsuAVjA+E/vS3rO65qReqzoebaDFGeGB89QjjurQOxdtwoOv2Amj1vM/CmTWhyt6UK8JJU8pJ87dB4wglvEQFUfXgVeSJfYy4KbQlBUWF2iu4t3UjcTZbFO3uOG2DNpl7z2T6bUN5cztOlTudpWVv86hmEAcdeeQzetvjNaWMpPhbFU2X79JYB1ciNxOu/rbQ== runner@github.com"
