- name: Add hardened SSH config
  copy:
    dest: /etc/ssh/sshd_config
    src: ../files/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Copy Fail2Ban jail.local configuration
  ansible.builtin.copy:
    src: ../files/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart fail2ban

- name: Ensure fail2ban service is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
