name: Ansible Check on Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read
  id-token: write

jobs:
  ansible-check:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST: ${{ vars.ANSIBLE_HOST || 'nubecita.dev' }}
      ANSIBLE_USER: ${{ vars.ANSIBLE_USER || 'runner' }}
      TIMEZONE: ${{ vars.TIMEZONE || 'Europe/Madrid' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Run Ansible playbook in check mode
        id: ansible-check
        run: |
          ansible-playbook -e ansible_user=$ANSIBLE_USER -e ansible_host=$ANSIBLE_HOST -e timezone=$TIMEZONE --check servers.yml | tee ansible_output.txt

      - name: Comment on pull request
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = require('fs').readFileSync('ansible_output.txt', 'utf8');

            const issueComment = `
            #### Ansible Check Output:
            \`\`\`
            ${output}
            \`\`\`
            `;

            // Retrieve existing comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            // Check if a comment from the bot already exists
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Ansible Check Output');
            });

            if (botComment) {
              // If a comment exists, update it
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: issueComment
              });
            } else {
              // If no comment exists, create a new one
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: issueComment
              });
            }
