name: Ansible Run on Pull Request Merged

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  pull-requests: write
  contents: read
  id-token: write

jobs:
  ansible-apply:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST: ${{ vars.ANSIBLE_HOST || 'nubecita.dev' }}
      ANSIBLE_USER: ${{ vars.ANSIBLE_USER || 'runner' }}
      TIMEZONE: ${{ vars.TIMEZONE || 'Europe/Madrid' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Run Ansible playbook
        id: ansible-check
        run: |
          ansible-playbook -e ansible_user=$ANSIBLE_USER -e timezone=$TIMEZONE servers.yml
